// C++ code
// Autor: Anthonny Michael Balbino Da Silva Santos

int buzzer = 2;
int DO = 262;
int RE = 294;
int MI = 330;
int FA = 349;
int SOL = 392;
int LA = 440;
int SI = 494;
int DO_2 = 523;

void setup()
{
  pinMode(2, OUTPUT);
}

void loop()
{
  /////////////////////////Começo da música Galinha Pintadinha
  tone(buzzer, DO_2);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, LA);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, MI);
  delay(650);
  tone(buzzer, DO_2);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, LA);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, FA);
  delay(650);
  tone(buzzer, SI);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, LA);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, SI);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, LA);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, SI);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, LA);
  delay(400);
  tone(buzzer, SI);
  delay(400);
  tone(buzzer, DO_2);
  delay(650);
  ////////////////////////////////////////////////////////// 
    
  ////////////////////////Primeira parte da música galinha pintadinha
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, DO_2);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, LA);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, MI);
  delay(400);
  tone(buzzer, MI);
  delay(500);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, DO_2);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, LA);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, FA);
  delay(500);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, SI);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, LA);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, SI);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, LA);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, SI);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, LA);
  delay(400);
  tone(buzzer, SI);
  delay(400);
  tone(buzzer, DO_2);
  delay(500);
  //////////////////////////////////////////////////////////////////
  
  //////////////////Segunda parte da música Galinha pintadinha 
    tone(buzzer, SOL);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, DO_2);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, LA);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, MI);
  delay(400);
  tone(buzzer, MI);
  delay(500);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, DO_2);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, LA);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, FA);
  delay(500);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, SI);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, LA);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, SI);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, LA);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, SI);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, LA);
  delay(400);
  tone(buzzer, SI);
  delay(400);
  tone(buzzer, DO_2);
  delay(500);
  ////////////////////////////////////////////////////////////////
  
  ///////////////Terceira parte da música Galinha Pintadinha
    tone(buzzer, SOL);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, DO_2);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, LA);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, MI);
  delay(400);
  tone(buzzer, MI);
  delay(500);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, DO_2);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, LA);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, FA);
  delay(500);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, SI);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, LA);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, SI);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, LA);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, SI);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, LA);
  delay(400);
  tone(buzzer, SI);
  delay(400);
  tone(buzzer, DO_2);
  delay(500);
  ////////////////////////////////////////////////////////////////////
  
  ////////////////////Ultima parte da música da Galinha Pintadinha
   tone(buzzer, DO_2);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, LA);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, MI);
  delay(650);
  tone(buzzer, DO_2);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, LA);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, FA);
  delay(650);
  tone(buzzer, SI);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, LA);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, SI);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, LA);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, SI);
  delay(400);
  tone(buzzer, SOL);
  delay(400);
  tone(buzzer, LA);
  delay(400);
  tone(buzzer, SI);
  delay(400);
  tone(buzzer, DO_2);
  delay(650);
  //////////////////////////////////////////////////////////////
}